Account/urls.py
from django.contrib.auth import login
from django.urls import path, include
from . import views
import  django.contrib.auth.views as auth_views


app_name='Account'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(template_name='Account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
]

Main/urls.py
from django.contrib import admin
from django.urls import path, include
from InvoiceApp.views import home
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('invoice/', include('InvoiceApp.urls')),
    path('account/', include('Account.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>Invoice</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'jquery/jqueryUI/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery/jqueryUI/jquery-ui.structure.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery/jqueryUI/jquery-ui.theme.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    {% block css %}
    {% endblock %}

</head>

<body>

    <div class="container">
        {% block header %}
        {% endblock %}
        {% block content %}

        {% endblock %}

    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'jquery/jqueryUI/jquery-ui.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>

</html>

templates/invoice_table.html
{% for invoice in invoices %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ invoice.name }}</td>
                    <td>{{ invoice.address }}</td>
                    <td>{{ invoice.email }}</td>
                    <td>{{ invoice.start_date }}-{{ invoice.end_date }}</td>
                    <td>{{ invoice.hours}}</td>
                    <td>{{ invoice.salary_per_hour}}</td>
                    <td>{{ invoice.total_salary }}</td>
                    <td>{{ invoice.status }}</td>
                    <td><a href="{{ invoice.get_absolute_url }}"><i class="bi bi-pencil-square"></i>| <a
                            href="{% url 'delete_invoice' invoice.id %}"><i class="bi bi-trash-fill"></i></a>
                    </td>
                    <td><a href="{% url 'generate_pdf' invoice.id %}"><i class="bi bi-file-earmark-pdf"></i> </a></td>

                </tr>
{% endfor %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary w-100">
    <a class="navbar-brand" href="#">Invoice</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ home }}">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item {{ create }}">
                <a class="nav-link" href="{% url 'create_invoice' %}">Create Invoice</a>
            </li>
        </ul>
        <ul class=" navbar-nav my-2 my-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Account:logout' %}">logout</a>
            </li>
        </ul>
    </div>
</nav>
<br>
<br>